app/db/models/Tour.py
from typing import Optional

from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Boolean

from app.db import Base


class Tour(Base):
    __tablename__ = "tours"

    id: Mapped[int] = mapped_column(primary_key=True)
    number: Mapped[int] = mapped_column(unique=True)
    name: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)
    is_reserved: Mapped[bool] = mapped_column(Boolean(), default=False)

    def __str__(self):
        return f"Тур до№ {self.number}: {self.name}"

app/__init__.py
from flask import Flask

from app.db.base import create_db
from app.routes.tour import tour_blueprint


app = Flask(__name__)
app.register_blueprint(tour_blueprint)


def main():
    create_db()
    app.run(debug=True, port=80)

app/db/__init__.py
from app.db.base import Base, Session
from app.db.models.Tour import Tour

app/routes/tour.py
from uuid import uuid4
import random

from flask import Blueprint, render_template, request, redirect, url_for, flash

from app.db import Session, Tour


tour_blueprint = Blueprint("tours", __name__)


@tour_blueprint.get("/")
def index():
    with Session() as session:
        tours = session.query(Tour).where(Tour.is_reserved == False).all()
        random.shuffle(tours)
        return render_template("index.html", tours=tours)


@tour_blueprint.route("/add_tour/", methods=["POST", "GET"])
def add_tour():
    if request.method == "POST":
        with Session() as session:
            number = request.form.get("number")
            name = request.form.get("name")

            tour = Tour(
                number=number,
                name=name,)
            session.add(tour)
            session.commit()
            return redirect(url_for("tours.index"))

    return render_template("reserve_tour.html")


@tour_blueprint.get("/reserve/<int:id>")
def reserve(id):
    with Session() as session:
        tour = session.query(Tour).where(Tour.id == id).first()
        tour.is_reserved = True
        session.commit()
        return render_template("reserved.html", tour=tour)


@tour_blueprint.get("/manage-tours/")
def manage_tours():
    with Session() as session:
        tours = session.query(Tour).all()
        return render_template("manage_tours.html", tours=tours)


@tour_blueprint.get("/del/<int:id>")
def del_tour(id):
    with Session() as session:
        tour = session.query(Tour).where(Tour.id == id).first()
        session.delete(tour)
        session.commit()
        return redirect(url_for("tours.manage_tours"))

app/templates/add_tour.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">

        <form action="{{ url_for('tours.add_tour') }}" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Номер туру</label>
                <input type="number" class="form-control" name="number">
            </div>
            <div class="mb-3">
                <label class="form-label">Назва туру</label>
                <input type="text" class="form-control" name="name">
            <div>
            <button type="submit" class="btn btn-primary">Додати</button>
        </form>

    </div>
  </div>
</div>
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>{% block title %} Головна сторінка {% endblock title %}</title>
</head>
<body class="p-5 bg-primary-subtle">
    {% include "navigation.html" %}
    <br><br>
    {% block content %}
    {% endblock content %}
</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% for tour in tours %}
    <div class="card">
      <div class="card-body">
          <h5 class="card-title">Назва туру : {{tour.name}}</h5>
          <p class="card-text"><em>Ціна туру: </em>{{ tour.price }}</p>
          <a href="{{url_for('tours.reserve', id=tour.id)}}">забронювати</a>
      </div>
      </div>
    {% endfor %}
{% endblock content %}

app/templates/manage_tours.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row align-items-center">
    {% for tour in tours %}
    <div class="col">
      <div class="card text-center" style="width: 18rem;">
        <img src="{{ tours.img_url }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ tour }}</h5>
          {% if tour.is_reserved %}
            <button class="btn btn-success">Зарезервовано</button>
          {% endif %}
          <a href="{{ url_for('tours.del_tour', id=tour.id)}}" class="btn btn-danger">Видалити тур</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock content %}

app/templates/navigation.html
<nav>
    <a class="btn btn-success" href="{{ url_for('tours.index') }}">Головна сторінка</a>
    <a class="btn btn-success" href="{{ url_for('tours.manage_tours') }}">Редагування турів</a>
    <a class="btn btn-success" href="{{ url_for('tours.add_tour') }}">Додати новий тур</a>
</nav>

app/templates/reserve_tour.html
{% extends "base.html" %}

{% block content %}
<div class="container text-center">
  <div class="row justify-content-md-center">
    <div class="col-md-auto">

        <form action="{{ url_for('tours.add_tour') }}" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Номер туру</label>
                <input type="number" class="form-control" name="number">
            </div>
            <div class="mb-3">
                <label class="form-label">Назва туру</label>
                <input type="text" class="form-control" name="name">
            <div>
            <button type="submit" class="btn btn-primary">Додати</button>
        </form>

    </div>
  </div>
</div>
{% endblock content %}

app/templates/reserved.html
{% extends "base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
  <img src="{{ tour.img_url }}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">Вітаю! Ви забронювали чудовий тур.</h5>
    <p class="card-text">{{ tour }}</p>
    <a href="{{ url_for('tours.index') }}" class="btn btn-primary">Перейти на головну сторінку</a>
  </div>
</div>
{% endblock content %}

app/templates/reserved_tour.html
{% extends "base.html" %}

{% block content %}
<div class="card" style="width: 18rem;">
  <img src="{{ room.img_url }}" class="card-img-top">
  <div class="card-body">
    <h5 class="card-title">Вітаю! Ви забронювали чудовий тур.</h5>
    <p class="card-text">{{ room }}</p>
    <a href="{{ url_for('rooms.index') }}" class="btn btn-primary">Перейти на головну сторінку</a>
  </div>
</div>
{% endblock content %}